name: "Conversation Rewards"
description: "Compute rewards for contributors' discussion on issues that are closed as complete."
inputs:
  settings:
    description: "The configuration settings to use"
    required: false
  authToken:
    description: "The token to log with Octokit"
    required: true
outputs:
  result:
    description: "The result containing all the rewards of the users"
    value: ${{ steps.main.outputs.result }}
runs:
  using: "composite"
  steps:
    - run: |
        yarn --cwd ${{ github.action_path }} --production=true
      id: install
      shell: bash
    - run: yarn --cwd ${{ github.action_path }} start
      shell: bash
      id: main
