name: "Conversation Rewards"
description: "Compute rewards for contributors' discussion on issues that are closed as complete."
inputs:
  issue_url:
    description: "The URL the the issue needing to be parsed"
    required: true
outputs:
  result:
    description: "The result containing all the rewards of the users"
    value: ${{ steps.main.outputs.result }}
runs:
  using: "composite"
  steps:
    - run: yarn --cwd ${{ github.action_path }} --production=true
      id: install
      shell: bash

    - name: Compute Rewards
      id: main
      run: yarn start --issue ${{ inputs.issue_url }}
      shell: bash

    - name: Set output
      run: echo "::set-output name=result::${{ steps.main.outputs.result }}"
      shell: bash
