name: "Conversation Rewards"
description: "Compute rewards for contributors' discussion on issues that are closed as complete."
outputs:
  result:
    description: "The result containing all the rewards of the users"
    value: ${{ steps.main.outputs.result }}
runs:
  using: "composite"
  steps:
    - run: |
        yarn --cwd ${{ github.action_path }} --production=true
      id: install
      shell: bash
    - run: yarn --cwd ${{ github.action_path }} start
      shell: bash
      id: main
