name: "Conversation Rewards"
description: "Compute rewards for contributors' discussion on issues that are closed as complete."
inputs:
  issue_url:
    description: "The URL the the issue needing to be parsed"
    required: true
outputs:
  result:
    description: "The result containing all the rewards of the users"
    value: ${{ steps.main.outputs.result }}
runs:
  using: "composite"
  steps:
    - run: |
        yarn --cwd ${{ github.action_path }} --production=true
        output=$(yarn --cwd ${{ github.action_path }} start --issue "${{ inputs.issue_url }}")
        echo "Output of calculations:"
        echo "$output"
        rewards=$(echo $output | pcregrep -M "^{[\s\S]*?}$")
        echo "Pushing results to REWARDS output"
        echo "REWARDS=$rewards" >> $GITHUB_OUTPUT
      id: main
      shell: bash
