name: Compute Rewards

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"

jobs:
  compute:
    name: Rewards
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      X25519_PRIVATE_KEY: ${{ secrets.X25519_PRIVATE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      NFT_MINTER_PRIVATE_KEY: ${{ secrets.NFT_MINTER_PRIVATE_KEY }}
      NFT_CONTRACT_ADDRESS: ${{ secrets.NFT_CONTRACT_ADDRESS }}

    steps:
      - run: ${{ toJSON(inputs) }}
        shell: cat {0}

      - name: Post starting comment to issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ inputs.authToken }}
          script: |
            const comment_body = 'Evaluating comments, please wait...';
            console.log(${{ inputs.eventPayload }})
            console.log(${{ fromJSON(inputs) }})
            console.log(${{ fromJSON(inputs.eventPayload) }})

            github.rest.issues.createComment({
              owner: ${{ inputs.eventPayload.repository.owner.login }},
              repo: ${{ inputs.eventPayload.repository.name }},
              issue_number: ${{ inputs.eventPayload.issue.number }},
              body: comment_body,
            });

#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: "20.10.0"
#

#
#      - name: Generate Rewards
#        uses: ./
