name: Run Local Tests

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
#      issueUrl:
#        description: "The URL of the issue needing to be parsed"
#        required: true
#      evmNetworkId:
#        description: "The EVM network ID to use"
#        required: true
#      evmPrivateEncrypted:
#        description: "The encrypted EVM private key"
#        required: true
      stateId:
        description: ""
      eventName:
        description: ""
      eventPayload:
        description: ""
      settings:
        description: ""
      authToken:
        description: ""
      ref:
        description: ""

jobs:
  test:
    name: Run Local Tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Action Test
        uses: Meniole/conversation-rewards@main
        with:
          issueUrl: ${{ inputs.issueUrl }}
